apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiranjoy-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kijoyin/kirans-web"
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: kiranjoy-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
